### ISSUE TITLE
[BUG] Retry Option in Twilight Thorn reverts KK to the Struggle Weapon

### ISSUE THREAD

**Issue by Frederyk-Strife** [TopazTK/KH-ReFined#100]
![image](https://user-images.githubusercontent.com/79901790/194403218-05d74f8f-6350-4912-b6ec-5050ed708b23.png)

**Comment by Frederyk-Strife** [comment]
if you beat it you keep Kingdom Key
![image](https://user-images.githubusercontent.com/79901790/194403705-6d06ca37-6ffd-43c9-8c41-509d8c1de43e.png)

**Comment by TopazTK** [comment]
Yea, this is an odd abnormality that I am really not sure how to solve.
It only happens for this instance though, that much I know of.
It is purely cosmetic, but I will look into it.
