### ISSUE TITLE
[BUG] KH2 Command Menu using PS2 textures

### ISSUE THREAD

**Issue by Frederyk-Strife** [TopazTK/KH-ReFined#102]
for some reason, on the latest version, the command menu in KH2 uses the non-remastered textures
![image](https://user-images.githubusercontent.com/79901790/195219790-ceb6dd45-e5a4-4611-bf0a-fa5bdbe6ec46.png)

**Comment by TopazTK** [comment]
Not Re:Fined related. May wanna check Panacea.
Closing.
