### ISSUE TITLE
No mini-maps in KH2

### ISSUE THREAD

**Issue by lekiscool** [TopazTK/KH-ReFined#104]
**Re:Fixed Version:**
ReFined v3.0, KH2 Critical Mode

**Game in Question:**
I am getting the alert that I've picked up the maps, but none of them are showing up in the UI.

**Bug Description:**
It looks like I didn't pick up the map.

**Reproduction Steps:**
I might be a KH2 Critical Mode-only bug.

**Screenshots/Video:**
The screen looks like it does before you pick up the map.

**Comment by TopazTK** [comment]
...are you sure you have the maps set to show?

**Comment by lekiscool** [comment]
I didn’t see an option for maps? On that note I also don’t see an option to
turn off vibration either.

Perhaps I am looking in the wrong place?

**Comment by TopazTK** [comment]
> I didn’t see an option for maps? On that note I also don’t see an option to turn off vibration either. Perhaps I am looking in the wrong place?

Maps have an option, vibrations do not anymore.
Turn that on and you should be gucci.

**Comment by lekiscool** [comment]
Ok I’ll take a look. Thank You.
