### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Jagbai** [TopazTK/KH-ReFined#108]
**Re:Fixed Version:**
v3.00

**Game in Question:**
Kingdom Hearts I

**Bug Description:**
Game crashes immediately after being booted up

**Reproduction Steps:**
1) Launch the Kingdom hearts 1.5 2.5 remix
2) Select Kingdom hearts 1
3) Game will crash

**Comment by TopazTK** [comment]
Invalid report format. Ignoring.
