### ISSUE TITLE
[BUG] Jack says "FAKE" instead of giving navigation options

### ISSUE THREAD

**Issue by tryashtar** [TopazTK/KH-ReFined#112]
**Re:Fixed Version:** 3.00

**Game in Question:** Kingdom Hearts II

**Bug Description:**
During the Gambler medallion part of Port Royal 2, I got Jack to say "FAKE" instead of pulling up the menu for navigation. Going in and out of the hold fixed it, so not a major issue.
Here's a video of what happened:

https://user-images.githubusercontent.com/26075577/208299327-f0902c57-d370-4020-9acb-34e58d358c6c.mp4

**Comment by MultiKoopa** [comment]
I have the same issue, but going in and out of the hold didn't fix it :\
