### ISSUE TITLE
[BUG] No saves for kingdom hearts 1using ReFined

### ISSUE THREAD

**Issue by Aaquin** [TopazTK/KH-ReFined#114]
When using the KH1 ReFined3.0 I have no saves googling led to nothing of use that i could find and looking through the issues tab all I could find is KH2 with no definiton of what was wrong

**Comment by drunkpyro** [comment]
This is something that I noticed when I changed the .exe for kingdom hearts 2.  All my saves disappeared. Luckily I made a copy of the original .exe and had to just put it back into the folder.  Got my saves back. I don't know if there is a way to move the saves into the new .exe or not. In any case, I can not use Refined on my current play-through.
