### ISSUE TITLE
[BUG] Audio bug entering different areas/screens.

### ISSUE THREAD

**Issue by bubbaj14** [TopazTK/KH-ReFined#118]
Upon entering an area a jingle will play randomly. This applies to rooms, new areas, entering a new world, exiting to the world map, etc. I read that that bug reports will be archived in lieu of 4.00, and that is fine, I just want to make sure it was brought up. Example video:

https://user-images.githubusercontent.com/118654363/210209202-d1a65c63-06e1-439f-ac32-d8b6d00b0826.mp4

It is inconsistent when it happens, it happens around every 3rd or 4th time changing locations.

**Comment by TopazTK** [comment]
This is normal. It is the Autosave saying "Yo! I saved your game!"
Closing.

**Comment by bubbaj14** [comment]
> This is normal. It is the Autosave saying "Yo! I saved your game!" Closing.

Hey there, sorry for reporting this as a bug. Thank you for your explanation.

**Comment by bubbaj14** [comment]
Is it possible to disable the sound effect for it? I am hearing it in cutscenes too.
