### ISSUE TITLE
[BUG] No AutoAttack & DualAudio

### ISSUE THREAD

**Issue by SWHSmash** [TopazTK/KH-ReFined#119]
**Re:Fixed Version:**
_Enter in the version of Re:Fixed where the bug occurs [Ex. v0.75]_
v3.00

**Game in Question:**
_Enter in the game where this is happening [Ex. Kingdom Hearts I]_
Kingdom Hearts II

**Bug Description:**
_What is the bug like? What does it do? Etc. [Ex. Magic Sorting locks the Command Menu]_
Auto Attack & Dual Audio won't work.

**Reproduction Steps:**
_Tell us, step by step, how to reproduce the bug._
--AutoAttack--
I checked the reFined.ini and set autoattack to true.
Also I try a separate autoattack lua from the KHPCSpeedrunTools section. The script got executed, but doesn't work ingame inCombat.

--Dual Audio--
I used everything in the ReadMe near the Installation, on the Dual Audio Part and I checked twice the correct patch & PatchManager Version 1.2.0.
But ingame I can't choose the language in the options.

**Screenshots/Video:**
_If the bug is difficult to understand, shoot a screenshot or a video link here!_
Down below the screen with the scripts I run atm, the used patches, the reFined.ini options and the scripts running screen with gameoptions in the background, where you can see there is nothing to change between english & japanese.
![kh2-issue-screen](https://user-images.githubusercontent.com/20990982/215021575-061c2e93-8672-4608-ae8e-9e746049b02d.png)

**Comment by TopazTK** [comment]
Refer to #117.
Closing.
