### ISSUE TITLE
KH2's Unlocked Framerate Problem

### ISSUE THREAD

**Issue by joshuakalejaiye** [TopazTK/KH-ReFined#120]
Release 2.75 Changelog
> Removed the removal of the 60FPS limiter due to the massive instability it caused. Sorry, Drahsid.

Under Credits in Readme
> Drahsid for his work on the 60FPS Framelock Issue.

I'd appreciate some help understanding this. From what I understand there is no way to play the ReFined version of KH2 at 120 FPS without random dips to 60. Is this accurate or does ReFined address this in another way?
The mod is excellent but I'm wondering if this is just an issue on my machine since the patched exe addresses the issue, or its just the nature of the game.

**Comment by TopazTK** [comment]
Refer to #117.
Closing.

**Comment by NolanHewitt** [comment]
Hoping that one day frame rates above 60fps will be possible : (
