### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by n1ckn4m3** [TopazTK/KH-ReFined#122]
**Re:Fixed Version:**
3.00

**Game in Question:**
BBS

**Bug Description:**
Crash to Desktop during Cinderella in-game cutscene

**Reproduction Steps:**
Fly to to Castle of Dreams, ,complete forced combat to begin in-game cutscene with Cinderella / Fairy Godmother.  Game CTD before end of cutscene reliably in the same place after the pumpkin turns into the carriage and Cinderella's attire has changed.

**Screenshots/Video:**
_If the bug is difficult to understand, shoot a screenshot or a video link here!_

**Comment by TopazTK** [comment]
Refer to #117. Closed.
