### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by alexbambo** [TopazTK/KH-ReFined#124]
Hey! I’m having an issue with KH2. I’m trying to synthesize mega potions and mega ethers to complete the Moogle journal entries, however, the recipe will not show up under “recipes”. Ive collected the “mega recipe” from Beast’s Castle and so there is no reason the recipe should not show up. In the recipe section of the Moogle shop, there is an item named “?????”, but nothing loads. As it’s the last recipe I need to synthesize to compete the Moogle journal entry, there’s nothing else I can do. @TopazTK 

Essentially, the bug I face is that the “Mega Recipe” that I picked up in Beast’s Castle will not load in the Moogle shop so that I can synthesize mega potions and mega ethers.

**Comment by TopazTK** [comment]
Refer to #117. Closed.
