### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by TheLegendOfLame** [TopazTK/KH-ReFined#125]
**Re:Fined\* Version:**
_Re:Fined v3.0_

**Game in Question:**
_Kingdom Hearts I_

**Bug Description:**
_Title screen is zoomed in after a soft reset._

**Reproduction Steps:**
_Presumably soft reset while a cutscene has a zoomed in camera angle. I don't recall what moment of the cutscene but it was during the cutscene where Donald and Goofy got picked as evidence in Wonderland._

**Comment by TopazTK** [comment]
Refer to #117. Closed.
