### ISSUE TITLE
[BUG] Quit Game option does not work

### ISSUE THREAD

**Issue by syah0910** [TopazTK/KH-ReFined#126]
**Re:Fined Version:**
v3.00

**Game in Question:**
Kingdom Hearts I
Kingdom Hearts II
Kingdom Hearts Birth by Sleep

**Bug Description:**
After selecting "Yes" on Quit Game Option's Popup Confirmation it just cancel the option, leaving no way to exit the game ( aside from force closing the game via Alt+F4 or Task Manager ).

**Reproduction Steps:**
At any time on Title Menu or Gameplay Menu ( via Start Button on Gamepad / 4 on Keyboard ), Press Esc keyboard button to access Game Settings then select Quit Game option and confirming "Yes" on the popup window.

**Comment by TopazTK** [comment]
Refer to #117. Closed.
