### ISSUE TITLE
[BUG] KHFM RE:FINED - Opening Chest during combat won't work.

### ISSUE THREAD

**Issue by GodnessOriginal** [TopazTK/KH-ReFined#127]
**Re:Fixed Version:**
_RE:Fined v3.00_

**Game in Question:**
_Kingdom Hearts I Final Mix (Italian)_

**Bug Description:**
_It's pretty simple, i've restared my run multiple times and whenever i'm in combat i still can't open chest like the normal game._

**Reproduction Steps:**
_Just start a new game and try to open one. I don't know if the fact that i'm playing on the Italian version of the game is a factor or not, since i can't change the region from the Epic Games store._

**Screenshots/Video:**
_Two screenshots attached_
![Screenshot (17)](https://github.com/TopazTK/KH-ReFined/assets/98845738/76ee8678-39f0-42c4-ae59-b3d36b4114cb)
![Screenshot (16)](https://github.com/TopazTK/KH-ReFined/assets/98845738/028234ec-631b-45b8-83e3-fda1c29374a8)

**Comment by TopazTK** [comment]
Refer to #117. Closed.
