### ISSUE TITLE
[BUG] is there anyway to get this working on linux/steamdeck

### ISSUE THREAD

**Issue by qvilligan** [TopazTK/KH-ReFined#129]
I want to get this running on the steam deck but no matter which version of lutris or proton i use, it doesnt load any game using the re:fine mods. is there any fix for this?

**Comment by Barjuh** [comment]
> I want to get this running on the steam deck but no matter which version of lutris or proton i use, it doesnt load any game using the re:fine mods. is there any fix for this?

https://youtu.be/i6MKeoRYVhc
