### ISSUE TITLE
[BUG] Retry breaks Underworld Cups

### ISSUE THREAD

**Issue by TopazTK** [TopazTK/KH-ReFined#131]
**Re:Fined Version:**
v4.10

**Game in Question:**
Kingdom Hearts II

**Bug Description:**
The Underworld Cups repeat infinitely, the player is not able to quit the cups.

**Reproduction Steps:**
-> Go into a cup.
-> ???
-> Profit!

**Screenshots/Video:**
Not necessary for this one but [here](https://cdn.discordapp.com/attachments/1139294925821853859/1156666036179964035/KINGDOM_HEARTS_HD_1.52.5_ReMIX_2023.09.27_-_21.57.16.03.mp4?ex=6515ccb0&is=65147b30&hm=e056dda70cfc9c4ebb67e12073bb1271b2ac987f4553506488edbc5681e13026&)!

**Comment by TopazTK** [comment]
> Seems to occur when you die in general

Please elaborate.

**Comment by SandeMC** [comment]
The Quit button works until the first death; if you die, even if you didnt Retry, you can't Quit anymore.

**Comment by TopazTK** [comment]
Noted.

**Comment by DejaDegausser** [comment]
I had this same bug in the core/mob battle before chair Xemnas. Everytime I beat the core and did the RC to continue it would loop me back to the start of the fight.

**Comment by TopazTK** [comment]
Noted.

> I had this same bug in the core/mob battle before chair Xemnas. Everytime I beat the core and did the RC to continue it would loop me back to the start of the fight.

**Comment by SandeMC** [comment]
Furthermore:
- Pressing "Quit" preserves everything you had pre-death, including used items and score (abuse-able)
- Pressing "Retry" i think resets everything to pre-fight state? Not sure

Both buttons resume the same round, though. And quitting before death works - only breaks if you die or if you retry once.

**Comment by TopazTK** [comment]
Fixed as of 3506a00fc7cabeb2527ea0f04509be1c9fad08c4.
