### ISSUE TITLE
[BUG] System.ArgumentOutOfRangeException regression

### ISSUE THREAD

**Issue by SandeMC** [TopazTK/KH-ReFined#135]
**Re:Fined Version:**
v4.10

**Game in Question:**
Kingdom Hearts II

**Bug Description:**
Re:Fined fails to launch, full error:
`System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. Parameter name: startIndex at System.ParseNumbers.StringToInt(String s, Int32 radix, Int32 flags, Int32* currPos) at System.Convert.ToUInt16(String value, Int32 fromBase) at ReFined.Helpers.InitConfig() at AxaFormBase.BaseSimpleForm.createInstance(AppInterface* _app, String title)`

**Reproduction Steps:**
- Update to 4.10
- ???
- It doesnt launch
- Downgrade to 4.05
- It launches

**Comment by SandeMC** [comment]
Fixed by removing `reFined.ini`.

**Comment by TopazTK** [comment]
Yea, the config changed to mitigate an issue with the v4.05 config.
