### ISSUE TITLE
[BUG] Resume missing in Atlantica

### ISSUE THREAD

**Issue by SandeMC** [TopazTK/KH-ReFined#136]
**Re:Fined Version:**
4.10

**Game in Question:**
Kingdom Hearts II

**Bug Description:**
The "Resume"/"Continue" button is missing when you pause a song in Atlantica.

**Reproduction Steps:**
- Start a song
- Pause
- Can't resume

**Screenshots/Video:**
![image](https://github.com/TopazTK/KH-ReFined/assets/70141395/47142272-9806-4a8e-a5cc-1a29602cfcf8)

**Comment by TopazTK** [comment]
It only seems to affect "some" songs. Will investigate.

**Comment by SandeMC** [comment]
> It only seems to affect "some" songs. Will investigate.

Don't have it on neither of the 5 myself.

**Comment by TopazTK** [comment]
That is extremely interesting. Will investigate **deeper**.

**Comment by TopazTK** [comment]
The problem was identified and fixed on KH-ReFined/KH2-MAIN.
