### ISSUE TITLE
[BUG] Prepare & Retry Causing Inventory Corruption

### ISSUE THREAD

**Issue by SandeMC** [TopazTK/KH-ReFined#137]
**Re:Fined Version:**
4.10

**Game in Question:**
Kingdom Hearts II

**Bug Description:**
ITS GONE
THE KEYBLADE IS GONE

**Reproduction Steps:**
- fight data bosses
- die like a loser
- try to prepare&retry thinking it'll make things easier
- change keyblades
- keyblade is gone
- cry in bed (optional)

**Screenshots/Video:**
https://github.com/TopazTK/KH-ReFined/assets/70141395/02dbeccf-54d4-4e0f-a401-f43430ace2fa
Instances of using prepare&retry:
https://www.youtube.com/live/XnB-khrzRsg&t=1209
https://www.youtube.com/live/XnB-khrzRsg&t=1363
https://www.youtube.com/live/XnB-khrzRsg&t=1438
https://www.youtube.com/live/XnB-khrzRsg&t=2190

Log:
[ReFined-02-10-2023.txt](https://github.com/TopazTK/KH-ReFined/files/12785473/ReFined-02-10-2023.txt)

**Comment by TopazTK** [comment]
Fixed as of f163a6cd4d0bda378da5e8b136747ee54f694aca.
Closing.
