### ISSUE TITLE
[BUG] EpicID Bypass isn't working.

### ISSUE THREAD

**Issue by SandeMC** [TopazTK/KH-ReFined#138]
**Re:Fined Version:**
4.10

**Game in Question:**
Any, I guess

**Bug Description:**
ReFined reports to de-DRM savefiles by de-attaching the Epic ID from the savefiles, but it's not the case and the game still says the file is corrupted when using somebody else's savefiles.

**Reproduction Steps:**
- Get the savefile off somebody else's epic account
- Try to use
- "Savefile is corrupted"

**Comment by TopazTK** [comment]
Regression. Fixed as of **v4.15**.
Closing.
