### ISSUE TITLE
[BUG] Prepare & Retry not restoring the drive gauge

### ISSUE THREAD

**Issue by SandeMC** [TopazTK/KH-ReFined#139]
**Re:Fined Version:**
4.15

**Game in Question:**
Kingdom Hearts II

**Bug Description:**
Using Prepare&Retry doesn't restore the drive gauge to the pre-fight value like Retry does

**Reproduction Steps:**
- Start a fight
- Use a drive form
- Die
- Use Prepare&Retry
- Drive gauge is still at the value from the last death

**Comment by TopazTK** [comment]
Fixed as of 5a96fc4df5da1757c74cd86077bbf00d7f11527f.
