### ISSUE TITLE
[BUG] Prepare and Retry as Riku Soflocks.

### ISSUE THREAD

**Issue by UnderClubLights** [TopazTK/KH-ReFined#140]
**Re:Fined Version:**
v4.15

**Game in Question:**
KH2

**Bug Description:**
When selecting prepare and retry after dying as riku the game will stay on a white screen 

**Reproduction Steps:**
Die as Riku during Xemnas fight
Select "prepare and retry" option 
The first time I did this the pause menu had 0 options to select and would soft lock but the 2nd time I tried to reproduce it the pause menu worked but the screen stayed white after unpausing (as shown in video) 

**Screenshots/Video:**
https://www.youtube.com/watch?v=IJPJCiIjZdc

**Comment by TopazTK** [comment]
Retry should not trigger there as the game has a built in Retry for the final battles. Will be fixed by blaacklist.

**Comment by TopazTK** [comment]
Fixed as of v4.20.
