### ISSUE TITLE
[BUG] Startup options do not reflect upon beginning the game

### ISSUE THREAD

**Issue by Vladabdf** [TopazTK/KH-ReFined#142]
**Re:Fined Version:**
4.15/4.17

**Game in Question:**
Kingdom Hearts II

**Bug Description:**
I usually select "Informative" autosaving as I like to know if the entire ReFined engine is still functional on a regular basis for testing purposes. However, upon beginning the game, the option is set instead to "Silent" without fail, even if I select "Disabled" in the `New Game` window. This is not exclusive; it happens for button prompts as well. They are always set to "Controller", even when I select "Keyboard" or "Automatic". I have not tested with dual audio or Heartless palettes. 

**Reproduction Steps:**
1. Choose "New Game". 
2. Select your options. 
3. Load into the game and proceed to enter the config menu ASAP. 
4. Notice options are not what we're chosen. 
5. Change them back to what is desired. 
6. Hope the game and engine don't crash. 
7. Get flashbanged by the game and have a PTSD flashback as the Ts raid Bomb Site A. 
8. Get no scoped by a scrub using a Scout. 
9. Sell your Karambit | Fade for approximately US$5000.
10. ???
11. Profit!

**Screenshots/Video:**
I am unable to provide one currently, but trust me, it's consistent.

**Comment by TopazTK** [comment]
Question: Are you using the Randomizer? This issue only happens with the Randomizer.

**Comment by Vladabdf** [comment]
Yes I am. Disregard.
