### ISSUE TITLE
Dream Drop Distance Support

### ISSUE THREAD

**Issue by TopazTK** [TopazTK/KH-ReFined#4]
This issue will be an indication of the progress being made on Dream Drop Distance support for Re:Fixed.

**Planned Changes:**

**In-Progress Changes:**

**Completed Changes:**
- Renaming of the config file from config28.dat to config_ddd.dat.
- Turning the Drop Gauge to be toggleable.
- Addition of the Soft Reset feature with START + SELECT as it's keybind.
- Being able to play in Critical Mode without a complete save.
- Removal of the 30FPS Framelimiter when in Cutscenes on 60FPS and above.
- Dual Audio Capabilities.
- Addition of Discord Rich Presence, customized for Dream Drop Distance.
- Autosave.

**Improbable Changes:**

**Comment by epic-bruh-moment** [comment]
Could I please request making Dream Eater progression optional?

DDD was a handheld game, that's why the whole "tamogachi" thing was more acceptable. Kinda like squares version of Nintendogs (?), however on pc and console it just feels like a genuine hinderance to the pacing.

**Comment by TopazTK** [comment]
I retain from making too many changes to the gameplay for reasons that may be imaginable, and I can make only one thing toggleable as of writing this comment.
Besides, it is a mechanic that is too bothersome to disable, and it will affect gameplay in a ridiculously complicated way.
I want to avoid that.

**Comment by Willow321Go** [comment]
Can you do anything about the enemies' prepensidy to stun lock you to death, or maybe am I just really bad at the game?

**Comment by asbel12** [comment]
What about skip dive mode like annyoning fight bees boss
It's annyoing everytime if U want play agian or always wait for bees come in

**Comment by aichi-n-crew** [comment]
> What about skip dive mode like annyoning fight bees boss It's annyoing everytime if U want play agian or always wait for bees come in

tbh it be a great newgame+ thing where dives are skipped while you already collected the keyblade for getting A rank on all dives
