### ISSUE TITLE
[REQUEST] Support for the JP Standard

### ISSUE THREAD

**Issue by almighty44** [TopazTK/KH-ReFined#40]
Could you please support the Japanese version as well as the global version?
I would be very happy if you would do so!

**Comment by TopazTK** [comment]
There are a couple issues with doing that.

-> The character set is devilishly different, as you may have guessed. I'd basically have to make a lookup table based "ToKHSCII" function for this.
-> The addresses are all over the place. So I'd have to also re-reverse the game to find *all* of them all over again.

It is definitely planned. But not for the forseeable future.

**Comment by almighty44** [comment]
Thanks for the reply
Glad to hear this is being planned.
