### ISSUE TITLE
Chain of Memories Support

### ISSUE THREAD

**Issue by TopazTK** [TopazTK/KH-ReFined#5]
This issue will be an indication of the progress being made on Chain of Memories support for Re:Fixed.

**Planned Changes:**

- Removal of the 30FPS Framelimiter when in Cutscenes on 60FPS and above.
- Addition of the Soft Reset feature with START + SELECT as it's keybind.
- Addition of Discord Rich Presence, customized for Chain of Memories.
- Renaming of the config file from config1525.dat to config_com.dat.
- Make Leon and Cloud Battles play "Face It!".
- I **think** I can make Zero EXP happen.

**In-Progress Changes:**
N/A

**Completed Changes:**
N/A

**Comment by RelaxedBatter** [comment]
Nice change would be to revert the D-pad functionality rotation in battle. PC version rotated all the D-pad actions in-battle 90 degrees.

Direction: PS2 -> PC
_UP_: Reload -> Shuffle right
_DOWN_: Shortcut -> Shuffle left
_LEFT_: Shuffle left -> Reload
_RIGHT_: Shuffle right -> Shortcut

The keybinding menu added to the PC port doesn't help, since changing D-pad bindings there also affects its use anywhere else, namely menus like the Review Deck menu.

**Comment by TopazTK** [comment]
> Nice change would be to revert the D-pad functionality rotation in battle. PC version rotated all the D-pad actions in-battle 90 degrees.
> 
> Direction: PS2 -> PC _UP_: Reload -> Shuffle right _DOWN_: Shortcut -> Shuffle left _LEFT_: Shuffle left -> Reload _RIGHT_: Shuffle right -> Shortcut
> 
> The keybinding menu added to the PC port doesn't help, since changing D-pad bindings there also affects its use anywhere else, namely menus like the Review Deck menu.

That, I have no idea how to do. But I can investigate.
But wasn't shuffling done exclusively on L1/R1?

**Comment by Doomsday33** [comment]
> That, I have no idea how to do. But I can investigate.
> But wasn't shuffling done exclusively on L1/R1?

Playing Chain of memories right now and even though the Leon tutorial doesn't tell you, you can shuffle with the D-pad as well as RelaxedBatter said. The really confusing rotated layout of the PC port vs the original PS2 layout feels very unnatural that it looks like a bug more than anything. Up for shuffle right and down for shuffle left. My brain can't adjust to that :'( .
