### ISSUE TITLE
[BUG] Auto Save During Theater Mode

### ISSUE THREAD

**Issue by YeeehTimmay** [TopazTK/KH-ReFined#68]
**Re:Fixed Version: 2.90**

**Game in Question: Kingdom Hearts II**
_Enter in the game where this is happening [Ex. Kingdom Hearts I]_

**Bug Description:**
The auto save function saves while using the theater mode in game. This overwrites whatever autosave you had before and also bugs the game out (example: watching one of the later TWTNW cutscenes will autosave to that location, and when attempting to load it causes the game to run all cutscenes after that point, one after the other.

**Reproduction Steps:**
Just start a cutscene in theater mode and once done, the auto save audio will sound and the auto save will be overwritten. 

**Screenshots/Video:**
![image](https://user-images.githubusercontent.com/55534065/182040091-0150a79c-f356-49ae-9562-09b33c27cca8.png) (after all TWTNW scenes play, the autosave sends you here. 
![image](https://user-images.githubusercontent.com/55534065/182040123-2944a6fb-c608-42de-8594-d5f915d7674a.png)

**Comment by TopazTK** [comment]
Known, will be fixed in v3.00.
Leaving open until fixed.
