### ISSUE TITLE
Treasures Menu Crash [BUG] 

### ISSUE THREAD

**Issue by sinopias** [TopazTK/KH-ReFined#79]
**Re:Fixed Version:**
v 3.0

**Game in Question:**
Birth by Sleep. 

**Bug Description:**
Opened up the menu -> Reports -> Treasures. Game crashes when I try to open it.

**Reproduction Steps:**
Didn't use the Dual Audio exe file. Played as Ventus on Proud Mode in the Snow White world. I was at the part where Ventus starts to chase the dwarves.
I also created a user id folder in the Save Data and Configuration folder respectively and put the files in there. Otherwise the game wouldn't recognize my data.

**Comment by TopazTK** [comment]
Known issue. Unfortunately BBS is being a total jerk right now.
Will be fixed in v3.10.

**Comment by TopazTK** [comment]
Ignored due to a complete rewriting decision.
