### ISSUE TITLE
[BUG] Framerate

### ISSUE THREAD

**Issue by DerFriseur** [TopazTK/KH-ReFined#81]
I've only encountered the problem in KH1 & KH2 because they are the only games I play in the collection. I've not seen it in the other games but I'm pretty sure it's there aswell.

I only have 144 hz monitors and if I cap my FPS to 60 it stutters like crazy, even on a G-Sync monitor.
But what is bugging me the most is the stuttering if I choose 120 or uncapped.
RTSS shows that there are no spikes in the frametime.
If a cutscene is running the frametime get really high spikes.
The game usually hovers around 70-90 frames (on a 3070)

I could fix it by forcing the refresh rate to 60 hz trough nvidia cp and setting the game fps to 60 but then the game has a very high latency which is also very annoying.
Any chance that this project will stabilize framerate on high refresh rates?

**Comment by TopazTK** [comment]
> I've only encountered the problem in KH1 & KH2 because they are the only games I play in the collection. I've not seen it in the other games but I'm pretty sure it's there aswell.
> 
> I only have 144 hz monitors and if I cap my FPS to 60 it stutters like crazy, even on a G-Sync monitor. But what is bugging me the most is the stuttering if I choose 120 or uncapped. RTSS shows that there are no spikes in the frametime. If a cutscene is running the frametime get really high spikes. The game usually hovers around 70-90 frames (on a 3070)
> 
> I could fix it by forcing the refresh rate to 60 hz trough nvidia cp and setting the game fps to 60 but then the game has a very high latency which is also very annoying. Any chance that this project will stabilize framerate on high refresh rates?

Disable G-Sync. G-Sync does not play nice with KH.
Closed as it is not a Re:Fixed bug.
