### ISSUE TITLE
Another BBS Crash (but this one is consistent) [BUG] 

### ISSUE THREAD

**Issue by ComponentGames** [TopazTK/KH-ReFined#82]
**Re:Fixed Version:**
_v.3.0

**Game in Question:**
_Birth By Sleep

**Bug Description:**
_In Aqua's Enchanted Dominion, during the cutscene where Aqua intercepts Ven talking to Maleficent, the game will always crash after Maleficent delivers the line "A key that opens the hearts of men, of entire worlds."

**Reproduction Steps:**
_Happened three times to me back to back

https://user-images.githubusercontent.com/112270489/187050793-44414b73-f72a-4a9c-832a-7bc85b6511db.mp4

a video link here!_

**Comment by TopazTK** [comment]
Closing.
![image](https://user-images.githubusercontent.com/95656963/187052055-ba6770c5-8b07-446d-8a65-57966acfe6ed.png)
