### ISSUE TITLE
Suggestion: A use for MP while in Valor form

### ISSUE THREAD

**Issue by Willow321Go** [TopazTK/KH-ReFined#83]
Valor Form has access to MP but no way to use it so my suggestion would be to add to the shortcut commands; the Combo Finishers from Valor Form's ability list but with an MP cost. Kind of like how Limit Form has it's Limits situated. This would allow for an easy coup de grace required by so many of the bosses in this game. so it would improve both a less interesting drive form and the overall gameplay loop of the game while improving speed-run times.

**Comment by TopazTK** [comment]
Not in the scope of Re:Fined.
Closing.
