### ISSUE TITLE
[BUG] Constant update loop for 3.00. Is it because of mods?

### ISSUE THREAD

**Issue by anttofm** [TopazTK/KH-ReFined#85]
Re:Fixed Version: 2.90

KH2FM
The game gives an update indication for 3.00. However, when I select 'yes' to update the game, the update seems to go halfway and then quit. Then I get locked into an endless update loop. Is it because I have other mods installed? Is there a way to update to 3.0 while keeping the mods I have intact?

**Comment by aichi-n-crew** [comment]
just update it manually and replace the EXEs with the new ones in 3.00. if you encounter bugs during that then you'll need to do a fresh install and redo everything again as mod compatibility may not be fully documented yet

**Comment by TopazTK** [comment]
3.00 update must be done manually.
Closing.
