### ISSUE TITLE
ReFined breaks Steam Deck compatibility. 

### ISSUE THREAD

**Issue by AvrgDerk** [TopazTK/KH-ReFined#86]
Game would launch in heroic games launcher until installing this newer exe. Now it refuses to launch at all until I revert to the old exe.  Last version that launches on deck is 2.10

**Comment by TopazTK** [comment]
Well, some stuff changed and a new method to launch was found on v3.00.
Until a tutorial is made, refer to the closed issues.
Closing.

**Comment by KHOmega** [comment]
> Game would launch in heroic games launcher until installing this newer exe. Now it refuses to launch at all until I revert to the old exe. Last version that launches on deck is 2.10

Video tutorial to launch Re:Fined 3.0 via Lutris is here: https://youtu.be/i6MKeoRYVhc
