### ISSUE TITLE
[BUG] combat chests KH1

### ISSUE THREAD

**Issue by romper008** [TopazTK/KH-ReFined#87]
Maybe I don't understand something, but in the list of fixes for KH1 there is bugfix for combat chests ("The player can now open chests and examine objects while in combat.") but it doesn't work. I click triangle on my gamepad next to the chest like you usual open them but in combat that's an order for your partners to attack your target.

**Comment by imsl0wer** [comment]
Having the same problem. It worked in version 2.90 though so not sure what happened there.

**Comment by TopazTK** [comment]
Bug. Resolved in v4.00.
Closing.
