### ISSUE TITLE
[BUG] BBS Treasure menu crash

### ISSUE THREAD

**Issue by acceleratorsouls** [TopazTK/KH-ReFined#89]
**Re:Fixed Version:**
v3.00
**Game in Question:**
Birth by Sleep

**Bug Description:**
Opening treasure journal menu causes weird stutter and crash.

**Reproduction Steps:**
Open the journal, then the treasure menu.

**Screenshots/Video:**
_If the bug is difficult to understand, shoot a screenshot or a video link here!_

**Comment by TopazTK** [comment]
All BBS bug reports are ignored due to the decision made to rewrite BBS completely.
Closing.
