### ISSUE TITLE
[BUG] Ice Cream Beat Dialog is broken when frame rate isn't 30fps

### ISSUE THREAD

**Issue by josecl200** [TopazTK/KH-ReFined#91]
**Re:Fixed Version:**
v2.90, v3.00

**Game in Question:**
Kingdom Hearts Birth By Sleep

**Bug Description:**
After selecting the option "You bet!" when talking to Dewey in Disney Town, the dialog won't proceed to song selection, instead the camera will stay in place and your only able to move your character (judging by Dewey's tracking when you move).

**Reproduction Steps:**

1. Set frame rate to 60 or higher
2. Talk to Dewey in Disney Town
3. Select "You bet!"

**Screenshots/Video:**
https://youtu.be/dr0-Qli8OkA

**Comment by TopazTK** [comment]
Ignored due to a complete rewrite of BBS being in the works.
Closing.
