### ISSUE TITLE
[BUG] Subtitles don't appear while playing with the japanese audio

### ISSUE THREAD

**Issue by Emalcat** [TopazTK/KH-ReFined#92]
**Re:Fixed Version:**
v3.00

**Game in Question:**
Kingdom Hearts 3D: Dream Drop Distance

**Bug Description:**
When I tried the dual audio feature on DDD, subtitles don't appear during the cutscenes.

**Reproduction Steps:**
1. Start the game, make sure subtitles are on
2. change language to japanese
3. save and reload
4. walk until you trigger a cutscene

**Comment by TopazTK** [comment]
Known issue. Subtitle Toggle is linked directly to JP Voice Toggle.
This is being investigated to severe this link.
