### ISSUE TITLE
[BUG] KH2 Switching to JP audio causes infinite load.

### ISSUE THREAD

**Issue by DottyOrb** [TopazTK/KH-ReFined#95]
**Re:Fixed Version:**
_Enter in the version of Re:Fixed where the bug occurs [Ex. v0.75]_
v3.00
**Game in Question:**
_Enter in the game where this is happening [Ex. Kingdom Hearts I]_
Kingdom Hearts II
**Bug Description:**
_What is the bug like? What does it do? Etc. [Ex. Magic Sorting locks the Command Menu]_
Game loads inifinitely when I select Japanese Audio in game, but Japanese audio plays fine in the theatre (whether it was intended to play in the theatre or not). Playing the UK version in case that has any bearing, mods installed:
- Re:Fined Dual Audio
- Refightable Sephiroth
- HD models (does not work)
- Original Title Screen HD
**Reproduction Steps:**
_Tell us, step by step, how to reproduce the bug._
Change the audio language to japanese, then either change rooms, go to the world map or save and exit to title then load the save. You will be presented wil an everlasting title screen, enjoy.
**Screenshots/Video:**
_If the bug is difficult to understand, shoot a screenshot or a video link here!_

**Comment by TopazTK** [comment]
You did not patch your game right. Try again. Make sure Re:Fined DA is patched last.
Closing.
