### ISSUE TITLE
[REQUEST] 16:10 Aspect Ratio Support

### ISSUE THREAD

**Issue by KHOmega** [TopazTK/KH-ReFined#98]
Requesting 16:10 Aspect Ratio support to support monitors of that degree and importantly, the Steam Deck.

Kingdom Hearts Re:Fined 3.0 somehow already has support built in for a full 16:10 Aspect Ratio at 1280x800, but other games in the collection do not.

**Comment by TopazTK** [comment]
KH1 does support it, but it does not work due to a bug.
Dunno if the rest will be supported.
