### ISSUE TITLE
[BUG] KH2FM Voives in cutscenes silent

### ISSUE THREAD

**Issue by Garydunlop00** [TopazTK/KH-ReFined#99]
**Re:Fixed Version:**
_Enter in the version of Re:Fixed where the bug occurs [Ex. v0.75]_
V3.00

**Game in Question:**
_Enter in the game where this is happening [Ex. Kingdom Hearts I]_
Kingdom Hearts 2

**Bug Description:**
_What is the bug like? What does it do? Etc. [Ex. Magic Sorting locks the Command Menu]_
Voices in cutscenes silent

**Reproduction Steps:**
_Tell us, step by step, how to reproduce the bug._
Not sure how to reproduce, All my cutscenes in game have voices silent, Normal KH2 exe doesnt have this problem.

**Screenshots/Video:**
_If the bug is difficult to understand, shoot a screenshot or a video link here!_

**Comment by TopazTK** [comment]
After you change the language, you have to go to the world map and come back.
If it still happens after that, you probably did not patch right.
Please check these factors and get back.
